### ISSUE TITLE
How to submit domain address when activating the license key?

### ISSUE THREAD

**Issue by nabeghe** [drazenbebic/license-manager-for-woocommerce#41] opened 2019-11-08 20:55 UTC
how to send domain address to 'v2/licenses/activate/{license_key}' route?!

**Comment by drazenbebic** [comment] 2019-11-13 18:57
@nabeghe,

If I understand correctly, you wish to verify the domain from where the license key is being activated from?

If that is so, then I must let you know that this is not possible at the moment. I do plan to add this feature in a future release.

Please correct me if I misunderstood anything.

**Comment by drazenbebic** [comment] 2019-11-28 13:44
Also, this is a duplicate of #21 

Please ask any and all questions there.

**Closed by drazenbebic** 2019-11-28 13:44 UTC
Labels: duplicate
