### ISSUE TITLE
Sending URL while activating

### ISSUE THREAD

**Issue by sebastienserre** [drazenbebic/license-manager-for-woocommerce#57] opened 2020-01-26 19:56 UTC
Hello,
Many thanks for your great plugin.
Should it be possible to send the url from where the key is activated?
Example: one of my plugin is activated on https://example.com, this url is sent through the API and stored in the Key data.

**Comment by duracelltomi** [comment] 2020-01-30 07:39
I have a pending pull request that could solve this request :-)

https://github.com/drazenbebic/license-manager-for-woocommerce/pull/56

**Comment by drazenbebic** [comment] 2020-12-07 10:55
I think that this is a duplicate of #21, or am I wrong?

**Comment by drazenbebic** [comment] 2021-03-15 20:07
Duplicate of #21

**Closed by drazenbebic** 2021-03-15 20:07 UTC
